version: "3.7"

services:
  flask:
    container_name: Flask
    build: .
    ports:
      - 5000:5000
    restart: always
    networks:
      - flask

networks:
  flask:
    name: TablesToCSV
    driver: bridge